name: ubuntu_x86

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: CMake set-up
      run: cmake -DCMAKE_BUILD_TYPE=Release .
    - name: make
      run: cmake --build .
      
