name: win_x86

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install BOOST and NASM
      run: |
        vcpkg install boost-system:x64-windows
        choco install nasm
    - name: CMake set-up
      run: cmake -S . `-D CMAKE_BUILD_TYPE=Release -DUSE_BOOST=ON`
    - name: make
      run: cmake --build . --config Release
